export const listaTeste = [
  {
    name: "Filé de tilapia assado com pure de batatas",
    description:
      "200g de file de tilápia, assado com tomate,     cebola, pimentão e especiarias, servido com purê de batatas e salada de alface e cenoura.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe7EM-Q0iUB4lnkeTC5kkVFO2vtHmDjHo2LA&usqp=CAU",
    category: "Peixes",
    ingredients: [
      "Tilapia",
      "Cebola",
      "Tomate",
      "Alface",
      "Pimentao",
      "Batata",
      "Creme de leite",
      "queijo",
      "Alho",
      "Cebola",
      "especiarias",
    ],
    note: 4,
  },
  {
    name: "Lasanha de carne moida",
    description:
      "350g de lasanha por pessoa, com massa fresca, e molho de carne moida, presunto, tomate e milho. Com cubertura de molho branco e mussarela.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPI4crzqm97dAPq1JXc3AEizzCVP--nHw7Kw&usqp=CAU",
    category: "massas",
    ingredients: [
      "Massa fresca",
      "Carne moida",
      "Tomate",
      "Presunto",
      "Mussarela",
      "Creme de leite",
      "Alho",
      "Cebola",
      "especiarias",
    ],
    note: 4,
  },
  {
    name: "Filé de tilapia assado com pure de batatas",
    description:
      "200g de file de tilápia, assado com tomate,     cebola, pimentão e especiarias, servido com purê de batatas e salada de alface e cenoura.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe7EM-Q0iUB4lnkeTC5kkVFO2vtHmDjHo2LA&usqp=CAU",
    category: "Peixes",
    ingredients: [
      "Tilapia",
      "Cebola",
      "Tomate",
      "Alface",
      "Pimentao",
      "Batata",
      "Creme de leite",
      "queijo",
      "Alho",
      "Cebola",
      "especiarias",
    ],
    note: 5,
  },
  {
    name: "Lasanha de carne moida",
    description:
      "350g de lasanha por pessoa, com massa fresca, e molho de carne moida, presunto, tomate e milho. Com cubertura de molho branco e mussarela.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPI4crzqm97dAPq1JXc3AEizzCVP--nHw7Kw&usqp=CAU",
    category: "massas",
    ingredients: [
      "Massa fresca",
      "Carne moida",
      "Tomate",
      "Presunto",
      "Mussarela",
      "Creme de leite",
      "Alho",
      "Cebola",
      "especiarias",
    ],
    note: 5,
  },
  {
    name: "Filé de tilapia assado com pure de batatas",
    description:
      "200g de file de tilápia, assado com tomate,     cebola, pimentão e especiarias, servido com purê de batatas e salada de alface e cenoura.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe7EM-Q0iUB4lnkeTC5kkVFO2vtHmDjHo2LA&usqp=CAU",
    category: "Peixes",
    ingredients: [
      "Tilapia",
      "Cebola",
      "Tomate",
      "Alface",
      "Pimentao",
      "Batata",
      "Creme de leite",
      "queijo",
      "Alho",
      "Cebola",
      "especiarias",
    ],
    note: 5,
  },
  {
    name: "Lasanha de carne moida",
    description:
      "350g de lasanha por pessoa, com massa fresca, e molho de carne moida, presunto, tomate e milho. Com cubertura de molho branco e mussarela.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPI4crzqm97dAPq1JXc3AEizzCVP--nHw7Kw&usqp=CAU",
    category: "massas",
    ingredients: [
      "Massa fresca",
      "Carne moida",
      "Tomate",
      "Presunto",
      "Mussarela",
      "Creme de leite",
      "Alho",
      "Cebola",
      "especiarias",
    ],
    note: 5,
  },
];
